spring:
  application:
    name:doc
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/common?currentSchema=common
    username: admin
    password: admin1!
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 1    # 연결 풀 초기화 (initialSize 관련)
      maximum-pool-size: 60            # maxActive에 해당
      minimum-idle: 5                  # minIdle에 해당
      connection-timeout: 10000        # maxWait에 해당
      connection-test-query: SELECT 1  # validationQuery에 해당
      keepalive-time: 300000           # timeBetweenEvictionRunsMillis와 유사
      idle-timeout: 60000              # minEvictableIdleTimeMillis에 해당
      leak-detection-threshold: 60000  # removeAbandonedTimeout과 관련된 기능
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.doc
  configuration:
    map-underscore-to-camel-case: true